# Generated by Django 3.2.4 on 2021-07-12 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idCategoria', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de Categoria')),
                ('Categoria', models.CharField(max_length=50, verbose_name='Nombre de la categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Periodista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombrePeriodista', models.CharField(max_length=50, verbose_name='nombre de periodista')),
                ('Edad', models.IntegerField(verbose_name='edad')),
                ('Ocupacion', models.CharField(max_length=200, verbose_name='ocupacion')),
                ('CantidadNoticias', models.IntegerField(verbose_name='cantidad de noticias')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.categoria')),
            ],
        ),
    ]
