# Generated by Django 3.2.4 on 2021-07-12 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombreNoticia', models.CharField(max_length=50, verbose_name='nombre de la noticia')),
                ('Fecha', models.DateField()),
                ('Ubicacion', models.CharField(max_length=200, verbose_name='ubicacion')),
                ('autor', models.CharField(max_length=50, verbose_name='periodista')),
                ('contenido', models.TextField()),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.categoria')),
            ],
        ),
    ]
