# Generated by Django 3.2.4 on 2021-07-12 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_noticia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='NombreNoticia',
            field=models.CharField(max_length=500, verbose_name='nombre de la noticia'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='autor',
            field=models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, to='core.periodista', verbose_name='periodista'),
        ),
    ]
