# Generated by Django 3.2.4 on 2021-07-13 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210712_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='imagen',
            field=models.ImageField(null=True, upload_to='noticias'),
        ),
        migrations.AddField(
            model_name='periodista',
            name='imagen',
            field=models.ImageField(null=True, upload_to='periodistas'),
        ),
    ]
