# Generated by Django 3.2.4 on 2021-07-13 03:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210712_2150'),
    ]

    operations = [
        migrations.CreateModel(
            name='tipoCATEGORIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.categoria')),
                ('titulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.noticia')),
            ],
        ),
    ]
