# Generated by Django 3.2.4 on 2021-07-13 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_tipocategoria'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tipocategoria',
            old_name='categoria',
            new_name='Categoria',
        ),
        migrations.AddField(
            model_name='tipocategoria',
            name='nombrecategoria',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
