# Generated by Django 3.2.4 on 2021-07-13 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210712_2347'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tipoCATEGORIA',
        ),
    ]
